import os
import re
import sys
from enum import Enum
from timeout_decorator import timeout
import xml.etree.ElementTree as ET


class TestStatus(Enum):
    FAILED = "FAILED"
    PASSED = "PASSED"
    SKIPPED = "SKIPPED"
    ERROR = "ERROR"
    XFAIL = "XFAIL"
    XPASS = "XPASS"

@timeout(30)
def parse_log_pytest(log: str) -> dict[str, str]:
    """
    Parser for test logs generated with PyTest framework

    Args:
        log (str): log content
    Returns:
        dict: test case to test status mapping
    """
    test_status_map = {}
    for line in log.split("\n"):
        for status in TestStatus:
            is_match = re.match(f"^(\S+)(\s+){status.value}", line)
            if is_match:
                test_status_map[is_match.group(1)] = status.value
                continue
    return test_status_map


@timeout(30)
def parse_log_mypy(log: str) -> dict[str, str]:
    """Parser for test logs generated by mypy"""
    test_status_map = {}
    for line in log.split("\n"):
        for status in [
            TestStatus.PASSED.value,
            TestStatus.FAILED.value,
        ]:
            if status in line:
                test_case = line.split()[-1]
                test_status_map[test_case] = status
                break
    return test_status_map


@timeout(30)
def parse_log_python_slugify(log: str) -> dict[str, str]:
    """Parser for test logs generated by un33k/python-slugify"""
    test_status_map = {}
    pattern = "^([a-zA-Z0-9_\-,\.\s\(\)']+)\s\.{3}\s"
    for line in log.split("\n"):
        is_match = re.match(f"{pattern}ok$", line)
        if is_match:
            test_status_map[is_match.group(1)] = TestStatus.PASSED.value
            continue
        for keyword, status in {
            "FAIL": TestStatus.FAILED,
            "ERROR": TestStatus.ERROR,
        }.items():
            is_match = re.match(f"{pattern}{keyword}$", line)
            if is_match:
                test_status_map[is_match.group(1)] = status.value
                continue
    return test_status_map


@timeout(30)
def parse_log_tornado(log: str) -> dict[str, str]:
    """Parser for test logs generated by tornadoweb/tornado"""
    test_status_map = {}
    for line in log.split("\n"):
        if line.endswith("... ok"):
            test_case = line.split(" ... ")[0]
            test_status_map[test_case] = TestStatus.PASSED.value
        elif " ... skipped " in line:
            test_case = line.split(" ... ")[0]
            test_status_map[test_case] = TestStatus.SKIPPED.value
        elif any([line.startswith(x) for x in ["ERROR:", "FAIL:"]]):
            test_case = " ".join(line.split()[1:3])
            test_status_map[test_case] = TestStatus.FAILED.value
    return test_status_map


@timeout(30)
def parse_log_paramiko(log: str) -> dict[str, str]:
    """Parser for test logs generated by paramiko/paramiko"""
    test_status_map = {}
    for line in log.split("\n"):
        for status in TestStatus:
            is_match = re.match(f"^{status.value}\s(\S+)", line)
            if is_match:
                test_status_map[is_match.group(1)] = status.value
                continue
    return test_status_map


@timeout(30)
def parse_log_autograd(log: str) -> dict[str, str]:
    """Parser for test logs generated by pytorch/pytorch"""
    test_status_map = {}
    for line in log.split("\n"):
        for status in TestStatus:
            is_match = re.match(f"^\[gw\d\]\s{status.value}\s(\S+)", line)
            if is_match:
                test_status_map[is_match.group(1)] = status.value
                continue
    return test_status_map


@timeout(30)
def parse_unittest_log(log: str) -> dict[str, str]:
    def _map_status(s: str) -> str:
        s = s.lower()
        if s == "ok":
            return TestStatus.PASSED.value
        if s == "fail":
            return TestStatus.FAILED.value
        if s == "error":
            return TestStatus.ERROR.value
        if s.startswith("skipped"):
            return TestStatus.SKIPPED.value
        if s == "expected failure":
            return TestStatus.XFAIL.value
        if s == "unexpected success":
            return TestStatus.XPASS.value
        return s

    def _normalize_id(method: str, qual: str) -> str:
        return f"{qual}.{method}"

    # 仅“头行”，没有 ... 的情况（verbosity 3 常见）
    HEADER_RE = re.compile(r"^(?P<method>\w+)\s+\((?P<qual>[^)]+)\)\s*$")

    # 单行完整：头 + ... + 状态（verbosity 1/2 常见，也可能出现在 3）
    INLINE_RE = re.compile(
        r"^(?P<method>\w+)\s+\((?P<qual>[^)]+)\).*?\s\.\.\.\s(?P<status>ok|FAIL|ERROR|skipped\b|expected failure|unexpected success)",
        re.IGNORECASE,
    )

    # 摘要行：FAIL:/ERROR: 前缀
    SUMMARY_RE = re.compile(
        r"^(?P<status>FAIL|ERROR):\s+(?P<method>\w+)\s+\((?P<qual>[^)]+)\)",
        re.IGNORECASE,
    )

    # 仅状态行：任意文本 + ... + 状态（docstring/说明里带 ... ok/FAIL/...）
    STATUS_ONLY_RE = re.compile(
        r"\s\.\.\.\s(?P<status>ok|FAIL|ERROR|skipped\b|expected failure|unexpected success)",
        re.IGNORECASE,
    )

    results: dict[str, str] = {}
    pending_id: str | None = None  # 用于 verbosity 3 的“头行->状态行”配对

    for raw in log.splitlines():
        line = raw.rstrip()
        if not line:
            continue

        # 1) 单行完整
        m = INLINE_RE.match(line)
        if m:
            test_id = _normalize_id(m.group("method"), m.group("qual"))
            results[test_id] = _map_status(m.group("status"))
            pending_id = None
            continue

        # 2) 摘要行（FAIL/ERROR 块）
        m = SUMMARY_RE.match(line)
        if m:
            test_id = _normalize_id(m.group("method"), m.group("qual"))
            results[test_id] = _map_status(m.group("status"))
            pending_id = None
            continue

        # 3) 仅头行（verbosity 3）
        m = HEADER_RE.match(line)
        if m:
            pending_id = _normalize_id(m.group("method"), m.group("qual"))
            continue

        # 4) 仅状态行（通常是头行后的下一行，含说明 + ... + 状态）
        if pending_id:
            m = STATUS_ONLY_RE.search(line)
            if m:
                results[pending_id] = _map_status(m.group("status"))
                pending_id = None
                continue

        # 其它行：忽略（如 trace、说明文字、空行等）

    return results


@timeout(30)
def parse_log_pytest_xdist(log: str) -> dict[str, str]:
    """
    输入整段 pytest 日志文本，返回 {nodeid: status}
    后出现的状态会覆盖先前的（例如重试/重复输出）。
    """
    # xdist: [gw0] [  0%] PASSED <nodeid> (0.12s)
    _STATUS = [status.value for status in TestStatus]
    _STATUS_RE = "|".join(_STATUS)
    _ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

    _PAT_XDIST = re.compile(
        rf"""
        ^\s*
        \[gw\d+\]\s+                # worker 前缀
        \[\s*\d+%\]\s+              # 进度
        (?P<status>{_STATUS_RE})\s+
        (?P<nodeid>.+?)             # nodeid 允许空格
        (?:\s+\([^)]+\))?           # 可选耗时
        \s*$
        """,
        re.VERBOSE,
    )

    # 标准：<nodeid> PASSED [ 14%] (0.12s)
    _PAT_STANDARD = re.compile(
        rf"""
        ^\s*
        (?P<nodeid>.+?)\s+
        (?P<status>{_STATUS_RE})
        (?:\s+\[\s*\d+%\])?         # 可选进度
        (?:\s+\([^)]+\))?           # 可选耗时
        \s*$
        """,
        re.VERBOSE,
    )

    # 兜底：PASSED <nodeid>
    _PAT_STATUS_FIRST = re.compile(
        rf"^\s*(?P<status>{_STATUS_RE})\s+(?P<nodeid>.+?)\s*$"
    )
    result: Dict[str, str] = {}
    for raw in log.splitlines():
        line = _ANSI_RE.sub("", raw).rstrip()

        m = _PAT_XDIST.match(line) or _PAT_STANDARD.match(line) or _PAT_STATUS_FIRST.match(line)
        if not m:
            continue

        nodeid = m.group("nodeid").strip()
        status = m.group("status").strip()
        if nodeid:
            result[nodeid] = status
    return result


@timeout(30)
def parse_log_pytest_xdist_v2(log: str) -> dict[str, str]:
    """
    输入整段 pytest 日志文本，返回 {nodeid: status}
    后出现的状态会覆盖先前的（例如重试/重复输出）。

    支持以下形式：
    - xdist：        [gw0] [  0%] PASSED <nodeid> (0.12s)
    - xdist（简化）：[gw0] PASSED <nodeid>
    - 标准：         <nodeid> PASSED [ 14% ] (0.12s)
    - 兜底：         PASSED <nodeid>

    参数：
        log:      完整日志字符串
        statuses: 可选的状态集合（如 {"PASSED", "FAILED", ...}）。
                  若不提供，优先从 TestStatus 读取；否则使用常见默认集合。
    """
    _STATUS = [status.value for status in TestStatus]
    _STATUS_RE = "|".join(re.escape(s) for s in _STATUS)
    _ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

    # xdist：允许 [  0% ] 可选
    _PAT_XDIST = re.compile(
        rf"""
        ^\s*
        \[gw\d+\]\s+                 # worker 前缀
        (?:\[\s*\d+%\]\s+)?          # 进度（可选）
        (?P<status>{_STATUS_RE})\s+
        (?P<nodeid>.+?)              # nodeid 允许空格
        (?:\s+\([^)]+\))?            # 可选耗时
        \s*$
        """,
        re.VERBOSE,
    )

    # 标准：<nodeid> PASSED [ 14%] (0.12s)
    _PAT_STANDARD = re.compile(
        rf"""
        ^\s*
        (?P<nodeid>.+?)\s+
        (?P<status>{_STATUS_RE})
        (?:\s+\[\s*\d+%\])?          # 可选进度
        (?:\s+\([^)]+\))?            # 可选耗时
        \s*$
        """,
        re.VERBOSE,
    )

    # 兜底：PASSED <nodeid>
    _PAT_STATUS_FIRST = re.compile(
        rf"^\s*(?P<status>{_STATUS_RE})\s+(?P<nodeid>.+?)\s*$"
    )

    result: dict[str, str] = {}
    for raw in log.splitlines():
        # 去除 ANSI 颜色码并右侧裁剪空白
        line = _ANSI_RE.sub("", raw).rstrip()
        if not line:
            continue

        m = (
            _PAT_XDIST.match(line)
            or _PAT_STANDARD.match(line)
            or _PAT_STATUS_FIRST.match(line)
        )
        if not m:
            # 例如只有 nodeid 的行（无状态）：直接忽略
            continue

        nodeid = m.group("nodeid").strip()
        status = m.group("status").strip()
        if nodeid:
            result[nodeid] = status  # 后出现覆盖先前
    return result


@timeout(30)
def parse_log_pytest_xdist_progress(log: str) -> dict[str, str]:
    _STATUS = [status.value for status in TestStatus]
    _STATUS_RE = "|".join(re.escape(s) for s in _STATUS)
    _ANSI_RE = re.compile(r"\x1b\[[0-9;]*m")

    # 2) 允许的 xdist 进度：百分比 [ 12% ] 或 计数 [  12/2031 ]
    _XDIST_PROGRESS = r"(?:\[\s*\d+%\]|\[\s*\d+\s*/\s*\d+\s*\])\s+"

    # xdist：带/不带进度
    _PAT_XDIST = re.compile(
        rf"""
        ^\s*
        \[gw\d+\]\s+                 # worker 前缀
        (?:{_XDIST_PROGRESS})?       # 进度（可选：百分比 或 计数）
        (?P<status>{_STATUS_RE})\s+
        (?P<nodeid>.+?)              # nodeid 允许空格与中括号
        (?:\s+\([^)]+\))?            # 可选耗时
        \s*$
        """,
        re.VERBOSE,
    )

    # 标准：<nodeid> PASSED [ 14%] (0.12s)
    _PAT_STANDARD = re.compile(
        rf"""
        ^\s*
        (?P<nodeid>.+?)\s+
        (?P<status>{_STATUS_RE})
        (?:\s+\[\s*\d+%\])?          # 可选进度（仅百分比常见）
        (?:\s+\([^)]+\))?            # 可选耗时
        \s*$
        """,
        re.VERBOSE,
    )

    # 状态在前：PASSED <nodeid>
    _PAT_STATUS_FIRST = re.compile(
        rf"^\s*(?P<status>{_STATUS_RE})\s+(?P<nodeid>.+?)\s*$"
    )

    # **新增** 仅 nodeid 的行（继承上一条状态）：
    # 采用保守启发：出现典型 nodeid 结构（至少包含 '::'）
    # 或以 'test/' 开头（常见路径）
    _PAT_NODEID_ONLY = re.compile(
        r"^\s*(?P<nodeid>(?:test/|tests/).+?::.+?|.+?::.+?)\s*$"
    )

    result: Dict[str, str] = {}
    last_status: str | None = None

    for raw in log.splitlines():
        # 去除 ANSI 颜色码并左右裁剪空白
        line = _ANSI_RE.sub("", raw).strip()
        if not line:
            continue

        m = (
            _PAT_XDIST.match(line)
            or _PAT_STANDARD.match(line)
            or _PAT_STATUS_FIRST.match(line)
        )

        if m:
            nodeid = m.group("nodeid").strip()
            status = m.group("status").strip()
            if nodeid:
                result[nodeid] = status
                last_status = status  # 记录以供“nodeid-only”行继承
            continue

        # 没有匹配到显式状态：尝试“仅 nodeid”的继承规则
        if last_status:
            mo = _PAT_NODEID_ONLY.match(line)
            if mo:
                nodeid = mo.group("nodeid").strip()
                if nodeid:
                    result[nodeid] = last_status  # 继承上一条状态
                continue

        # 其余情况：忽略（比如无关日志）
        continue

    return result


def parse_pytest_xml_report(xml_file_path):
    """
    解析 pytest 的 JUnit XML 报告，提取通过和失败的测试函数名。
    此版本会先移除文件第一行的 '[STDOUT]' 标记（如果存在）
    并根据 classname 和 name 属性构建测试标识符。
    """
    if not os.path.exists(xml_file_path):
        return None, None, None

    passed_tests = []
    failed_tests = []
    skipped_tests = []

    try:
        with open(xml_file_path, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        if lines and lines[0].strip() == '[STDOUT]':
            content = "".join(lines[1:])
        else:
            content = "".join(lines)
            
        if not content.strip():
            return [], [], []

        root = ET.fromstring(content)
        
        for testcase in root.iter('testcase'):
            classname = testcase.get('classname')
            name = testcase.get('name')

            if not name:
                continue

            full_test_name = f"{classname}::{name}"
            
            failure = testcase.find('failure')
            error = testcase.find('error')
            skipped = testcase.find('skipped')

            if failure is not None or error is not None:
                failed_tests.append(full_test_name)
            elif skipped is not None:
                skipped_tests.append(full_test_name)
            else:
                passed_tests.append(full_test_name)
                
        return passed_tests, failed_tests, skipped_tests
        
    except ET.ParseError as e:
        # 在并行模式下，减少打印的干扰，只在关键时刻警告
        # print(f"Warning: XML ParseError in {xml_file_path}: {e}.")
        return None, None, None
    except Exception as e:
        print(f"An unexpected error occurred while parsing {xml_file_path}: {e}")
        return None, None, None


MAP_REPO_TO_PARSER = {
    "parse_log_pytest": parse_log_pytest,
    "parse_log_autograd": parse_log_autograd,
    "parse_log_paramiko": parse_log_paramiko,
    "parse_log_mypy": parse_log_mypy,
    "parse_log_tornado": parse_log_tornado,
    "parse_log_python_slugify": parse_log_python_slugify,
    "parse_unittest_log": parse_unittest_log,
    # "parse_log_pytest_xdist": parse_log_pytest_xdist,
    "parse_log_pytest_xdist": parse_log_pytest_xdist_v2,
    "parse_log_pytest_xdist_v2": parse_log_pytest_xdist_v2,
    "parse_log_pytest_xdist_progress": parse_log_pytest_xdist_progress,
    'parse_pytest_xml_report': parse_pytest_xml_report,
}
